### ISSUE TITLE
CSS tweaks

### ISSUE THREAD

**Issue by gyuris** [gyuris/openlyrics-prototype#1]
The 1e4fd21 CSS tweaks should be removed.

Currently we have an issue with CSS for XML. CSS for HTML (XSLT driven) is not affected. Both issue is coming from [non supported](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) [`:has()`](https://drafts.csswg.org/selectors-4/#relational) "parent" CSS selector. 

#### 1. The `tweak="newline"` problem

In `<chord>` tags we need to allow line breaks (`<br/>`):

```xml
nem látlak Té<chord root="A" structure="min">ged,<br/>mégis érez</chord>lek
```

To handle this with CSS, we have to use the non supported `:has()` selector:

```css
song[version="0.9"] lines > chord:has(> br) {
  display: inline;
}
song[version="0.9"] lines > chord:has(> br)::before {
  position: absolute;
  display: inline-block;
}
```
#### 2. The `tweak="nested"` problem

To support more that one chord on one syllable we need to use nested `<chord>` tags:

```xml
<chord root="A"><chord root="G"><chord root="D">A</chord></chord></chord>lle<chord root="D">luja</chord>
```
Handling with CSS:
```css
song[version="0.9"] lines chord[root]:has(> chord[root]) {
  line-height: 0;
}
song[version="0.9"] lines chord[root]:has(> chord[root])::before {
  display: inline-block;
  width: 100%;
  position: relative;
  top: .5rem;
  text-align: right;
}
```

## Summary

1. We need a better solution for these problems without tweaking the XML source.
2. This is a CSS problem, affects: 
  - [browsers](https://caniuse.com/#feat=css-has), 
  - ~~Prince~~: Prince 12/13 [supports](https://www.princexml.com/doc/css-refs/#logical-combinations) the `:has()` selector
  - ~~WeasyPrint~~:  Currently has no support for XML documents (and no support for `:has()` selector)

**Comment by gyuris** [comment]
First attempt, but no success:
```css
lines {
  display: block;
  margin: 1rem;
  line-height: 2rem;
  padding-top: .5rem;
}
lines br::before {
  content: "\A"; 
  white-space: pre-line;
}
chord {
  display: inline flow-root;
}
chord::before {
  content: attr(root) attr(structure) attr(bass);
  display: block;
}
```
Second attempt with flex layout modell, but no success:

```css
lines {
  display: block;
  margin: 1rem;
  line-height: 2rem;
  padding-top: .5rem;
}
lines br::before {
  content: "\A"; 
  white-space: pre-line;
}
chord {
  display: inline flex;
  flex-direction: column;
}
chord::before {
  content: attr(root) attr(structure) attr(bass);
}
```
